// articles
export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_ARTICLES_BY_ID_REQUESTS = 'FETCH_ARTICLES_BY_ID_REQUESTS';
export const FETCH_ARTICLES_BY_ID_SUCCESS = 'FETCH_ARTICLES_BY_ID_SUCCESS';
export const FETCH_ARTICLES_BY_ID_ERROR = 'FETCH_ARTICLES_BY_ID_ERROR';

//topics
export const FETCH_TOPICS_REQUEST = 'FETCH_TOPICS_REQUEST';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';

export const FETCH_TOPIC_ARTICLES_REQUEST = 'FETCH_TOPIC_ARTICLES_REQUEST';
export const FETCH_TOPIC_ARTICLES_SUCCESS = 'FETCH_TOPIC_ARTICLES_SUCCESS';
export const FETCH_TOPIC_ARTICLES_ERROR = 'FETCH_TOPIC_ARTICLES_ERROR';

//users
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const FETCH_USERID_REQUEST = 'FETCH_USERID_REQUEST';
export const FETCH_USERID_SUCCESS = 'FETCH_USERID_SUCCESS';
export const FETCH_USERID_ERROR = 'FETCH_USERID_ERROR';

//comments
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

//post new content
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_ERROR = 'ADD_ARTICLE_ERROR';

//votes
export const VOTE_REQUEST = 'VOTE_REQUEST';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_ERROR = 'VOTE_ERROR';
